server:
  port: 8080

spring:
  application:
    name: zuul-api-gateway
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/


zuul:
  routes:
    uaa:
      sensitive-headers:
      path: /uaa/**
      serviceId: auth-service
      stripPrefix: false
  add-proxy-headers: true


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9100/uaa/user
